### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by zcdliuwei** [liangxuCHEN/no_fit_polygon#10]
你好，看了您的仓库，非常有趣，想请教一个问题，有没有什么办法，能生成如下的图案：
![image](https://user-images.githubusercontent.com/36565076/175450751-4412e49e-9136-4ba7-b6f0-283952151144.png)
也就是，如何把一些预先提供的子元素，比如一条鱼、一只水母、一个篮球等进行摆放，使其形成一个预定义的形状，比如圆环圆盘、U型闭合等。
期待您的回复

**Comment by liangxuCHEN** [comment]
你可以看看这个原版的例子，https://github.com/Jack000/SVGnest， 这里面有特定图形的排列，理论上是可以的
