### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by Wenwu1998** [liangxuCHEN/no_fit_polygon#11]
请问nfp_function里的from Polygon import Polygon 文件是什么可以发一下吗，参考一下

**Comment by Wenwu1998** [comment]
请问凹多边形是暂时还没考虑吗

**Comment by liangxuCHEN** [comment]
Polygon 是一个公开库，用pip install Polygon3 就可以，如果是python2.x, 应该是pip install Polygon2， 这个项目只是把别人项目js版本变成python版本
