### ISSUE TITLE
polygon library ?

### ISSUE THREAD

**Issue by jeanroukas** [liangxuCHEN/no_fit_polygon#12]
Hello,
I don't know if you will have time to see this, and I know this project is almost 4 years old.
I tried to make it work as a learning project, but I am not sure what polygon library you are using.
I tried with Polygon3, but it did not work.

I get this error with python test_nfp.py :

Traceback (most recent call last):
File "C:\Users\lprad\gcode_clay_processor\experimental\nfp\test_nfp.py", line 28, in
content_loop_rate(best, n, loop_time=2) # T7 , T4
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:-\experimental\nfp\nfp_function.py", line 678, in content_loop_rate
draw_result(res['placements'], n.shapes, n.container, n.container_bounds)
File "C:-\experimental\nfp\nfp_function.py", line 392, in draw_result
shapes.append(Polygon(contour))
^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

I'm into building some sort of CAM nesting script.
Have a good day.

**Comment by liangxuCHEN** [comment]
hi, Jeanroukas. Sorry to reponse your question so late. I think you can try to import dxf  (ex: `input_utls.input_polygon('dxf_file/E6.dxf')`),  make sure the input data is correct. As you know, it is project 4 years old, i almost forget it Good luck!
