### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by zz290213** [liangxuCHEN/no_fit_polygon#2]
陈先生你好，我对临界多边形的原理大概的学了一下，然后用CAD画了几个图形放入您的代码中跑了一下，结果图形出现了部分重叠，请问可以解答一下是什么原因造成的吗。

**Comment by liangxuCHEN** [comment]
能截图看看吗？

发自我的 iPhone

**Comment by zz290213** [comment]
非常感谢您的回复，我画了两个矩形和四个三角形，出来的结果便是这样，是图形间隔空间的问题吗。


------------------ 原始邮件 ------------------
发件人: "liangxu chen"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 晚上9:22
收件人: "liangxuCHEN/no_fit_polygon"<no_fit_polygon@noreply.github.com>;
抄送: "王文正"<290213618@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [liangxuCHEN/no_fit_polygon] 有个小问题 (#2)



能截图看看吗？ 
 
 发自我的 iPhone

**Comment by liangxuCHEN** [comment]
我看不到图片，你可以先看看导入dxf文件后，能否画出闭合的图形，然后调一下参数看看，我这个也是demo，学习一下，要深入了解，还是看回去svgnesting

发自我的 iPhone

**Comment by zz290213** [comment]
好的，十分感谢




------------------ 原始邮件 ------------------
发件人: "liangxu chen"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 上午9:55
收件人: "liangxuCHEN/no_fit_polygon"<no_fit_polygon@noreply.github.com>;
抄送: "王文正"<290213618@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [liangxuCHEN/no_fit_polygon] 有个小问题 (#2)



我看不到图片，你可以先看看导入dxf文件后，能否画出闭合的图形，然后调一下参数看看，我这个也是demo，学习一下，要深入了解，还是看回去svgnesting
 
 发自我的 iPhone
