### ISSUE TITLE
test_nfp.py中使用的E6.dxf文件能否上传一下？

### ISSUE THREAD

**Issue by WestXu** [liangxuCHEN/no_fit_polygon#4]

**Comment by liangxuCHEN** [comment]
你好, 我在另外一个项目里面放了这个文档, 

https://github.com/liangxuCHEN/irregular_packing/blob/master/f6.dxf

具体画法, 是用cad, 直接线段画图, 导出的时候选择dxf格式就可以了.

这个项目只是一个不成熟的测试, 所以没有写什么记录, 不好意思.

**Comment by WestXu** [comment]
好的谢谢。另外请问一下您这些repo之间有什么关系？

**Comment by liangxuCHEN** [comment]
irregular_packing 是写一下测试例子, no_fit_polygon 是一个比较完整的demo

**Comment by WestXu** [comment]
了解。多谢解答。
