### ISSUE TITLE
利用率

### ISSUE THREAD

**Issue by tuzhirun** [liangxuCHEN/no_fit_polygon#5]
你好，你这个里面的rate是什么，是利用率吗？如果不是，请问你是怎么定义的？
这是遗传算法写的吧？谢谢大佬

**Comment by liangxuCHEN** [comment]
Rate是利用率, 定义是有使用的面积/ 总面积,  算法是用遗传算法写, 没有最优解, 只是当前有限次数里面的,最好结果.
