### ISSUE TITLE
增加不规则的Container的问题

### ISSUE THREAD

**Issue by ZhuChiYu** [liangxuCHEN/no_fit_polygon#6]
您好，请问我在增加不规则的Container时，会出现“图形坐标出错”的问题，这个如何解决呢？谢谢

**Comment by liangxuCHEN** [comment]
请问你怎样添加数据？可以把数据复制到邮件里面给我看看

发自我的 iPhone

**Comment by ZhuChiYu** [comment]
[cid:8e4266b3-9865-434b-8242-52b471371ac7@apcprd01.prod.exchangelabs.com]

2019年12月26日 下午8:35，liangxu chen <notifications@github.com<mailto:notifications@github.com>> 写道：

请问你怎样添加数据？可以把数据复制到邮件里面给我看看

发自我的 iPhone

**Comment by ZhuChiYu** [comment]
好的，数据已经发到您的Gmail了
